buildscript {
    repositories {
        maven { url = "https://fabricmc.net" }
    }
    dependencies {
        // Change this line to force 1.15.5 or remove the block entirely
        classpath "net.fabricmc:fabric-loom:1.15.5"
    }
}

plugins {
    id "net.fabricmc.fabric-loom" version "1.15.5" apply false
}

subprojects {
    group = "boti.doc"
    version = "1.4.0"
}
