pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://repo.papermc.io/repository/maven-public/" }
    }
    plugins {
        id 'net.fabricmc.fabric-loom' version '1.15.5'
        id 'com.gradleup.shadow' version '8.3.6'
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        mavenCentral()
        maven { url = "https://maven.fabricmc.net/" }       // For Fabric Loader
        //maven { url = "https://minecraft.net" } // For vanilla Minecraft jars
        maven { url = "https://repo.papermc.io/repository/maven-public/" } // For Paper API modules
    }
}

rootProject.name = "DocBoti-timers"

include "common:timer-core"
include "common:playertimer-core"
include "common:smptimer-core"

include "fabric:playertimer-fabric"
include "fabric:smptimer-fabric"

include "paper:playertimer-paper"
include "paper:smptimer-paper"

